// Regenerates the route tables in COMBOS.md (between the <!-- routes --> markers)
// from the fighter data: every route by difficulty, with its hits and damage
// (the lowest against any opponent). Run with: node tools/combotable.js
var fs = require('fs'), path = require('path'), vm = require('vm');
var ROOT = path.join(__dirname, '..');
var ctx = { console: console, Math: Math }; ctx.window = ctx; vm.createContext(ctx);
var html = fs.readFileSync(path.join(ROOT, 'index.html'), 'utf8');
var re = /<script src="(src\/(?:fg\.js|engine\/[^"]+|data\/[^"]+))"><\/script>/g, mt;
while ((mt = re.exec(html))) vm.runInContext(fs.readFileSync(path.join(ROOT, mt[1]), 'utf8'), ctx, { filename: mt[1] });
var FG = ctx.FG;

var out = [];
FG.ROSTER.forEach(function (d) {
  out.push('### ' + d.name + ' (' + d.archetype.toLowerCase() + ', ' + d.theme.toLowerCase() + ')', '');
  out.push('| Route | Level | Inputs | Hits | Meter | Damage |', '| --- | --- | --- | --- | --- | --- |');
  ['easy', 'medium', 'hard'].forEach(function (lv) {
    d.combos.filter(function (c) { return c.difficulty === lv; }).forEach(function (c) {
      var dmg = Math.min.apply(null, FG.ROSTER.map(function (o) { return FG.runCombo(d, o, c).damage; }));
      out.push('| ' + c.name + ' | ' + lv + ' | ' + c.notation + ' | ' + c.hits.length + ' | ' + (c.meter ? c.meter + (c.meter > 1 ? ' bars' : ' bar') : '-') + ' | ' + dmg + ' |');
    });
  });
  out.push('');
});
var file = path.join(ROOT, 'COMBOS.md'), md = fs.readFileSync(file, 'utf8');
var a = md.indexOf('<!-- routes -->'), b = md.indexOf('<!-- /routes -->');
if (a < 0 || b < 0) throw new Error('COMBOS.md needs <!-- routes --> and <!-- /routes --> markers');
md = md.slice(0, a) + '<!-- routes -->\n<!-- generated by node tools/combotable.js -->\n\n' + out.join('\n') + md.slice(b);
fs.writeFileSync(file, md);
console.log('Wrote the route tables in COMBOS.md');
